variable "redhat_ami" {}
variable "instance_type" {}
variable "pub_key_name" {}
variable "ssl_cert" {}
variable "nexus_name" {}
variable "nc_account_id" {}
variable "nc_api_id" {}
variable "vpc_id" {}
variable "nexus_subnets" {}
variable "nexus_domain" {}
variable "name" {}
variable "domain" {}
variable "subnet_id" {}