variable "ami-redhat" {}
variable "ansible-sg" {}
variable "subnet-id" {}
variable "keypair" {}
variable "name" {} 
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "privatekey" {}
variable "nexus-ip" {}
variable "stage-discovery" {}
variable "prod-discovery" {}
variable "nc-account-id" {}
variable "nc-api-id" {}
