variable "ubuntu_ami" {}
variable "instance_type" {}
variable "subnet_id" {}
variable "sonarqube-sg" {}
variable "pub_key_name" {}
variable "sonar_name" {}
variable "sonar-subnets" {}
variable "ssl-cert" {}
variable "nc-account-id" {}
variable "nc-api-id" {}